### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by p-ranav** [p-ranav/hypergrep#14]
- Documentation
  - [ ] USAGE_GIUDE.md elaborating on available features
- Features
  - [x] https://github.com/p-ranav/hypergrep/issues/9
  - [x] https://github.com/p-ranav/hypergrep/issues/8
  - [x] https://github.com/p-ranav/hypergrep/issues/7
  - [x] https://github.com/p-ranav/hypergrep/issues/6
- Tests
  - [x] Update fmt dependency to v10.0 
  - [x] Line number is correct for small files with both stdout and pipe
  - [x] Line number is correct for large files with both stdout and pipe
  - [x] print_only_matching works correctly with both stdout and pipe
  - [x] count works correctly with both stdout and pipe
  - [x] symlinks are correctly ignored with both git repos and other directories
  - [x] binary files are ignored using NULL byte detection and file extensions
  - [x]  Use HS_FLAG_SOM_LEFTMOST only if not `print_matching_only` and not `stdout` and not `--columns`
